force-app/main/default/objects/Query__c/Query__c.object-meta.xml
<CustomObject>
    <description>Contains the Questions and Answers</description>
    <label>Query</label>
    <nameField>
        <displayFormat>QA-{00000}</displayFormat>
        <label>Query Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Query__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <inlineHelpText>Enter your answer here</inlineHelpText>
    <label>Answer</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Query__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/ep_questionAnswerClass.cls
public without sharing class ep_questionAnswerClass {
 @AuraEnabled(cacheable=true)
    public static List<quesWrap> getQuestionList(){
        List<Query__c> query=[SELECT Id,Question__c,Answer__c FROM Query__c];
        List<quesWrap> quesList= new List<quesWrap>();
        for(Query__c q:query){
        quesWrap qs= new quesWrap();
        qs.Question=q.Question__c;
        qs.Answer=q.Answer__c;
        quesList.add(qs);
        }
       
        return quesList;
    }
    
    @AuraEnabled
    public static void saveQuestion(String ques,String ans,String recType){
        system.debug(ques+ans+recType);
        List<Query__c> queryList= new List<Query__c>();
        Query__c q=new Query__c();
        q.Question__c=ques;
        q.Answer__c=ans;
        q.RecordTypeId=recType;
        queryList.add(q);
        insert queryList;
    }
    
   public class quesWrap{
    @AuraEnabled public String Question;
    @AuraEnabled public String Answer;
    }    
}