force-app/main/default/objects/Jira_Comment__c/Jira_Comment__c.object-meta.xml
<CustomObject>
    <label>Jira Comment</label>
    <nameField>
        <displayFormat>JC-{000000}</displayFormat>
        <label>Jira Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jira Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Jira_Comment__c/fields/Comment_Body__c.field-meta.xml
<CustomField>
    <fullName>Comment_Body__c</fullName>
    <label>Comment Body</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Jira_Comment__c/fields/Mod_Date__c.field-meta.xml
<CustomField>
    <fullName>Mod_Date__c</fullName>
    <formula>TEXT( DAY(  DATEVALUE(LastModifiedDate) ) )+&apos;/&apos;+TEXT( MONTH( DATEVALUE(LastModifiedDate)   ) )+&apos;/&apos;+TEXT( YEAR(  DATEVALUE(LastModifiedDate)  ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mod Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Jira_Comment__c/fields/Sprint_Element__c.field-meta.xml
<CustomField>
    <fullName>Sprint_Element__c</fullName>
    <label>Sprint Element</label>
    <referenceTo>Sprint_Element__c</referenceTo>
    <relationshipLabel>Jira Comments</relationshipLabel>
    <relationshipName>Jira_Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sprint__c/Sprint__c.object-meta.xml
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sprint__c/fields/Sprint_Date__c.field-meta.xml
<CustomField>
    <fullName>Sprint_Date__c</fullName>
    <label>Sprint Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sprint_Element__c/Sprint_Element__c.object-meta.xml
<CustomObject>
    <label>Sprint Element</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Sprint Element Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sprint Elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sprint_Element__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
                <default>true</default>
                <label>Low</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sprint_Element__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <label>Sprint</label>
    <referenceTo>Sprint__c</referenceTo>
    <relationshipLabel>Sprint Elements</relationshipLabel>
    <relationshipName>Sprint_Elements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sprint_Element__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sprint_Element__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <label>Tag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tag_set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sprint_Element__c/fields/Task_Name__c.field-meta.xml
<CustomField>
    <fullName>Task_Name__c</fullName>
    <label>Task Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ep_JiraController.cls
public without sharing class ep_JiraController {
    
    @AuraEnabled(cacheable=true)
    public static jiraWrap getJiraId(String jId){
        system.debug('Called');
        String finalString;
        Date toDate=Date.today();
        Integer days;
        List<Sprint__c> sprintList=[SELECT Id,Name FROM Sprint__c];
        jiraWrap retWrap= new jiraWrap();
        retWrap.sprintList=sprintList;
        if(jId=='null'){
            Sprint__c currSprint=[SELECT Id,Sprint_Date__c,Name FROM Sprint__c WHERE Sprint_Date__c>=:toDate ORDER BY Sprint_Date__c ASC LIMIT 1];
            List<Sprint_Element__c> elemList= [SELECT Id,Name,Status__c,Task_Name__c,Tag__c,Description__c,Priority__c FROM Sprint_Element__c WHERE Sprint__c=:currSprint.Id];    
            days=toDate.daysBetween(currSprint.Sprint_Date__c);
            finalString= currSprint.Id+'++'+currSprint.Name+'++'+days;
            retWrap.detailString=finalString;
            retWrap.elementList=elemList;
        }
        else{
            Sprint__c currSprint=[SELECT Id,Sprint_Date__c,Name FROM Sprint__c WHERE Id=:jId];
            List<Sprint_Element__c> elemList= [SELECT Id,Name,Status__c,Task_Name__c,Tag__c,Description__c,Priority__c FROM Sprint_Element__c WHERE Sprint__c=:currSprint.Id];    
            days=toDate.daysBetween(currSprint.Sprint_Date__c);
            finalString= currSprint.Id+'++'+currSprint.Name+'++'+days; 
            retWrap.detailString=finalString;  
            retWrap.elementList=elemList;   
        }
        return retWrap;
    }

    @AuraEnabled(cacheable=true)
    public static List<Jira_Comment__c> getComments(String recId){
        List<Jira_Comment__c> commList= [SELECT Id, Sprint_Element__c,Comment_Body__c,Mod_Date__c FROM Jira_Comment__c WHERE Sprint_Element__c= :recId ORDER BY Mod_Date__c DESC];
        return commList;
    }

    @AuraEnabled
    public static void deleteElement(String recId){
        Sprint_Element__c el=[SELECT Id FROM Sprint_Element__c WHERE Id=: recId];
        delete el;
    }
    
    
    public class jiraWrap{
        @AuraEnabled public String detailString;
        @AuraEnabled public List<Sprint__c> sprintList;
        @AuraEnabled public List<Sprint_Element__c> elementList;
        
    }
}