force-app/main/default/objects/Daily_Task__c/Daily_Task__c.object-meta.xml
<CustomObject>
    <label>Daily Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Task__c/fields/isRecurring__c.field-meta.xml
<CustomField>
    <fullName>isRecurring__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recurring</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Daily_Task__c/fields/newTestTime__c.field-meta.xml
<CustomField>
    <fullName>newTestTime__c</fullName>
    <formula>LEFT(TEXT( TIMEVALUE(Scheduled_Time__c )+19800000 ), 2)+&apos;:&apos;+MID(TEXT( TIMEVALUE(Scheduled_Time__c )+19800000 ), 4, 2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>newTestTime</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Task__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning</fullName>
            </value>
            <value>
                <fullName>Afternoon</fullName>
            </value>
            <value>
                <fullName>Night</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Task__c/fields/Test_Time__c.field-meta.xml
<CustomField>
    <fullName>Test_Time__c</fullName>
    <formula>VALUE(LEFT(TEXT( TIMEVALUE(Scheduled_Time__c )+19800000 ), 2))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Test Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Task__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/History__c/History__c.object-meta.xml
<CustomObject>
    <label>History</label>
    <nameField>
        <label>History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/History__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>History_Category_List</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/History__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ep_HistoryClass.cls
public without sharing class ep_HistoryClass {
    
    public class InfoCls{
        @AuraEnabled public String Id;
        @AuraEnabled public String Name;
        @AuraEnabled public String Subject;
        @AuraEnabled public Boolean Important;
        @AuraEnabled public String Session;
        @AuraEnabled public Double Value;
        @AuraEnabled public String Description;
    }

@AuraEnabled(cacheable=true)
    public static List<InfoCls> getDateSpecTasks(String dateSelected){
        Date sampDate=Date.valueOf(dateSelected);
        List<Daily_Task__c> dList= new List<Daily_Task__c>();
        if(dateSelected==''){
             dList= [SELECT Id,Name,Subject__c,Completed__c,Description__c,Important__c,Scheduled_Time__c,Test_Time__c,newTestTime__c,Scheduled_Date__c,Session__c,Value__c
                                    FROM Daily_Task__c WHERE Scheduled_Date__c =: Date.today() OR isRecurring__c= True ORDER BY Session__c];
        }
        else{
             dList= [SELECT Id,Name,Subject__c,Completed__c,Description__c,Important__c,Scheduled_Time__c,Test_Time__c,newTestTime__c,Scheduled_Date__c,Session__c,Value__c
                                    FROM Daily_Task__c WHERE Scheduled_Date__c =: sampDate OR isRecurring__c= True ORDER BY Session__c];
        }
        
        List<InfoCls> infList= new List<InfoCls>();
        for(Daily_Task__c d:dList){
            InfoCls i= new InfoCls();
            i.Name=d.Name;
            i.Subject=d.Subject__c;
            i.Important=d.Important__c;
            i.Session=d.Session__c;
            i.Value=d.Value__c;
            i.Id=d.Id;
            i.Description=d.Description__c;
            infList.add(i);
        }
        return infList;
    }
    
    
 @AuraEnabled(cacheable=true)
    public static List<History__c> getHistoryElements(List<String> categoryList, Decimal fromDate, Decimal toDate){
     
    List<History__c> histList= new List<History__c>();    
    
    String category='';
        for(String singleCat:categoryList){
            category=category+';'+singleCat;
        }
    String finalQuery='SELECT Id,Name,Category__c,Year__c,Description__c FROM History__c WHERE ';    
    String dateAdd='Year__c <= '+toDate+' AND Year__c >= '+fromDate;
    String categAdd= '(\''+category+'\')'; 
       
    finalQuery=finalQuery+dateAdd+'AND Category__c includes '+categAdd;
     try{   
    histList=Database.query(finalQuery); 
        } 
        Catch(Exception e){
            system.debug('No Records');
        }
    return histList;    
    }  
    
    
 @AuraEnabled(cacheable=true)
    public static List<Daily_Task__c> getDailyTasks(Date d){
     
    List<Daily_Task__c> taskList= new List<Daily_Task__c>();    
if(d!=null){
        taskList=[SELECT Id,Name,Subject__c,Completed__c,Description__c,Important__c,Scheduled_Time__c,Test_Time__c,newTestTime__c,Scheduled_Date__c,Session__c,Value__c,isRecurring__c FROM Daily_Task__c WHERE Scheduled_Date__c =: d  OR isRecurring__c=true];
     
    }
    else{
        taskList=[SELECT Id,Name,Subject__c,Completed__c,Description__c,Important__c,Scheduled_Time__c,Test_Time__c,newTestTime__c,Scheduled_Date__c,Session__c,Value__c,isRecurring__c FROM Daily_Task__c WHERE Scheduled_Date__c =: Date.today() OR isRecurring__c=true];
     
    }   
    return taskList;    
    }
    
 @AuraEnabled
    public static void changeTaskStatus(String recordId){
        Daily_Task__c samp= [SELECT Id, Completed__c FROM Daily_Task__c WHERE Id=:recordId];
        if (samp.Completed__c){
            samp.Completed__c=false;
        }
        else{
            samp.Completed__c=true;
        }
        Update samp;
    }
    
 @AuraEnabled
    public static void deletePrevTasks(){
        try{
        List<Daily_Task__c> samp= [SELECT Id, Completed__c FROM Daily_Task__c WHERE Scheduled_Date__c <: Date.today()];
        Delete samp;
        }
        Catch (Exception e){
            system.debug('public static void deletePrevTasks()');
        }
    }   
    
      
 @AuraEnabled
    public static void deleteOneTask(Id recId){
        try{
        Daily_Task__c samp= [SELECT Id, Completed__c FROM Daily_Task__c WHERE Id=:recId];
        Delete samp;
        }
        Catch (Exception e){
            system.debug('public static void deleteOneTask(Id recId)');
        }
    }    
    
}