force-app/main/default/objects/Revision__c/Revision__c.object-meta.xml
<CustomObject>
    <label>Revision</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Revision Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revision</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revision__c/fields/Date2__c.field-meta.xml
<CustomField>
    <fullName>Date2__c</fullName>
    <formula>Scheduled_Date__c + 7</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Revision__c/fields/Date3__c.field-meta.xml
<CustomField>
    <fullName>Date3__c</fullName>
    <formula>Scheduled_Date__c + 30</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date3</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Revision__c/fields/Date4__c.field-meta.xml
<CustomField>
    <fullName>Date4__c</fullName>
    <formula>Scheduled_Date__c + 90</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date4</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Revision__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <label>Reference</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/ep_RevisionClass.cls
public with sharing class ep_RevisionClass {
  
    @AuraEnabled(cacheable=true)
    public static List<revWrap> getRevisionQuestions(String count){
        List<revWrap> finalList=new List<revWrap>();
        Date todayDate=Date.today();
        List<Revision__c> revlist= new List<Revision__c>();
        if(count!='All'){
        revlist=[SELECT Id, Question__c, Scheduled_Date__c, Date2__c, Date3__c, Date4__c,Reference__c FROM Revision__c 
                                   WHERE Scheduled_Date__c=:todayDate 
                                   OR Date2__c=:todayDate 
                                   OR Date3__c=:todayDate 
                                   OR Date4__c=:todayDate ORDER BY CreatedDate ASC];
        }
        else{
            revlist=[SELECT Id, Question__c, Scheduled_Date__c, Date2__c, Date3__c, Date4__c,Reference__c FROM Revision__c
            ORDER BY CreatedDate ASC];    
                                }
        //system.debug('revlist---- '+finalList);
        for(Revision__c r:revlist){
            revWrap samp= new revWrap();
            samp.Question=r.Question__c;
            samp.Reference=r.Reference__c;
            finalList.add(samp);
        }
        system.debug('revlist---- '+finalList);
        return finalList;
    }
    
  @AuraEnabled
    public static void addRevisionQuestion(String ques, String ref){
        List<Revision__c> revLists=new List<Revision__c>();
        Date sDate=Date.today();
        Revision__c rev= new Revision__c();
        rev.Question__c= ques;
        rev.Scheduled_Date__c=sDate;
        rev.Reference__c=ref;
        revLists.add(rev);
        Insert revLists;
    }
    
    
     public class revWrap{
        @AuraEnabled public String Question;
        @AuraEnabled public String Reference;
    }
}